baseURL = 'https://www.emavs.fr'
title = 'École de Musique Associative du Val Sierckois'
languageCode = 'fr-fr'

# theme as git submodule
theme = "ananke"

DefaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  text_color = ""
  author = "École de Musique Associative du Val Sierckois"
  description = "École de Musique Associative du Val Sierckois"
  favicon = "/images/logos/logo-emavs.png"
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gold"
  recent_posts_number = 10

  [[params.ananke_socials]]
      name = "rss"
      url = "/post/index.xml"
      label = "Abonnez vous à notre flux RSS"

  [[params.ananke_socials]]
      name = "facebook"
      url = "https://www.facebook.com/people/Ecole-de-musique-associative-du-val-sierkois/100085957481811/"
      label = "Facebook"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "L'actualité"
    weight = 200
    identifier = "posts"
    url = "/post/"

[permalinks]
  post = '/:year/:month/:day/:slug/'
  evenements = 'evenements/:year/:slug/'
