baseURL = 'https://www.emavs.fr'
title = 'EMAVS'
languageCode = 'fr-fr'

# theme as git submodule
theme = "ananke"

DefaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  text_color = ""
  author = "EMAVS"
  description = "École de Musique Associative du Val Sierckois"
  favicon = "/images/logo.png"
  site_logo = "/images/logo-1-small.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10

  [[params.ananke_socials]]
      name = "facebook"
      url = "https://fr-fr.facebook.com/emmanuelle.emavs/"
      label = "Facebook"

  [[params.ananke_socials]]
      name = "github"
      url = "https://github.com/EMAVS"
      label = "GitHub"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "L'actualité"
    weight = 200
    identifier = "posts"
    url = "/post/"

[permalinks]
  post = '/:year/:month/:day/:slug/'
